---

- hosts: all
  become: true
  tasks: 

  - name: Install apache and php package
    package: 
      name:
       - "{{ apache_package }}"
       - "{{ php_package }}"
      state: latest
      update_cache: yes
  
- hosts: db_servers
  become: true
  tasks:  

  - name: install mariadb package 
    package:
      name: mariadb-server
      state: latest
    
 

  

