---

- hosts: all
  become: true
  tasks: 

  - name: Update Amazon worker nodes packages and cache
    tags: always
    yum:
      name: '*'
      state: latest

  - name: Install apache and php package
    tags: http,php
    package: 
      name:
       - "{{ apache_package }}"
       - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: copy default html file for site
    tags: httpd,php
    copy:    
     src: default_site.html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644

  

