---

- hosts: all
  become: true
  tasks: 

  - name: Install apache2 package
    yum: 
      name: httpd

  - name: Start apache2 service
    service:
      name: httpd
      state: started
      enabled: true
  
  - name: add php support for apache
    apt: 
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


 

  
